import '../styles/globals.css'
import Header from "../components/Header";

export const metadata = {
  title: 'Dalle-2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/* Prompt Input*/}
        {/* Page Section */}
        {children}
      </body>
    </html>
  )
}
